package citas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Poner_Asunto_Ventana extends VerticalLayout {
	protected Label ponerAsunto;
	protected ComboBox comboAsunto;
	protected Button nuevoAsunto;
	protected HorizontalLayout nuevoAsuntoLayout;
	protected Label labelNuevoAsunto;
	protected TextField nuevoNombreAsunto;

	public Poner_Asunto_Ventana() {
		Design.read(this);
	}
}
