package citas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ver_Informacion_de_Cliente_Ventana extends FormLayout {
	protected TextField verNombre;
	protected TextField verDireccion;
	protected TextField verTelefono;
	protected Button cerrar;

	public Ver_Informacion_de_Cliente_Ventana() {
		Design.read(this);
	}
}
